import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import Header from "@/components/Shared/Header";
import Footer from "@/components/Shared/Footer";
import "./globals.css";

const rubik = Rubik({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["cyrillic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
